
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 3430
 */
public class frmMain extends javax.swing.JFrame {
    
    Pila pila;
    List<Carta> baraja;
    List<Carta> mazoDisplay;
    int contadorCartas;
    
    String[] tipo = { "♣", "♠", "♥", "♦" };
    String[] valores = { "A", "2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K" };
    String[] colores = { "#000000", "#000000", "#FF0000", "#FF0000" };

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setResizable(false);
        this.setTitle("Poker");
     
        barajear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnTomarCarta = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblCartaActual = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstDisplay = new javax.swing.JList<>();
        lblContadorCartas = new javax.swing.JLabel();
        btnBarajear = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        btnTomarCarta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTomarCarta.setText("Tomar carta");
        btnTomarCarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTomarCartaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Carta actual");

        lblCartaActual.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblCartaActual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lstDisplay.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstDisplay);

        lblContadorCartas.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        lblContadorCartas.setForeground(new java.awt.Color(255, 255, 255));
        lblContadorCartas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContadorCartas.setText("0 / 52");

        btnBarajear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBarajear.setText("Barajear de nuevo");
        btnBarajear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarajearActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mazocartas.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnTomarCarta, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCartaActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(lblContadorCartas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBarajear, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblContadorCartas)
                        .addGap(18, 18, 18)
                        .addComponent(lblCartaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTomarCarta, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(btnBarajear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBarajearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarajearActionPerformed
        barajear();
    }//GEN-LAST:event_btnBarajearActionPerformed

    private void btnTomarCartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTomarCartaActionPerformed
        tomarUnaCarta();
    }//GEN-LAST:event_btnTomarCartaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBarajear;
    private javax.swing.JButton btnTomarCarta;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCartaActual;
    private javax.swing.JLabel lblContadorCartas;
    private javax.swing.JList<String> lstDisplay;
    // End of variables declaration//GEN-END:variables

    private void iniciarPoker() {
        baraja = new ArrayList<>();
        
        for (int i = 0; i < tipo.length; i++) {
            String tipoA = tipo[i];
            String colorA = colores[i];
            for (int j = 0; j < valores.length; j++) {
                String valorA = valores[j];
                baraja.add(new Carta(valorA, tipoA, colorA));
            }
        }
    }

    private void barajear() {
        contadorCartas = 0;
        iniciarPoker();
        lblCartaActual.setText("");
        setContador();
        mazoDisplay = new ArrayList<>();
        setListaDisplay();
        
        pila = new Pila();
        //ramdon llenar los datos 
        while(!baraja.isEmpty()) {
            Random rand = new Random();
            int posicionAzar = rand.nextInt(baraja.size());
            Carta azar = baraja.remove(posicionAzar);
            pila.push(azar);
        }
        
        JOptionPane.showMessageDialog(this, "Baraja Lista");
    }

    private void setContador() {
        lblContadorCartas.setText( contadorCartas + " / 52" );
    }

    private void setListaDisplay() {
        DefaultListModel modelo = new DefaultListModel();
        Carta[] cartasDisplay = new Carta[mazoDisplay.size()];
        
        for (int i = 0; i < mazoDisplay.size(); i++) {
            Carta c = mazoDisplay.get(i);
            cartasDisplay[i] = c;
        }
        for (int i = 0; i < cartasDisplay.length; i++) {
            modelo.addElement( cartasDisplay[i].getValor() + " " + cartasDisplay[i].getTipo() );
        }
        
        this.lstDisplay.setModel(modelo);
    }

    private void tomarUnaCarta() {
        if(!pila.isEmpty()) {
            
            Carta carta = pila.pop();
            contadorCartas++;
            setContador();
            
            mazoDisplay.addFirst(carta);
            setListaDisplay();
            
            lblCartaActual.setText( carta.getValor()+ " " + carta.getTipo());
            lblCartaActual.setForeground( Color.decode(carta.getColor()) );
            
        }else{
            JOptionPane.showMessageDialog(this, "La baraja está vacia");
        }
    }
}
